version: "3.9"

services:
  postgres:
    container_name: likeme_one-postgres
    restart: always
    image: postgres:14.1
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
  django:
    container_name: likeme_one-django
    build:
      context: ./src/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    depends_on:
      - postgres
