# Generated by Django 3.2.8 on 2021-11-06 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_app.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Name')),
                ('name_ru', models.CharField(db_index=True, max_length=32, verbose_name='Название')),
                ('name_uk', models.CharField(db_index=True, max_length=32, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhotographerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Name')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Phone Number')),
                ('viewed', models.BooleanField(default=False, verbose_name='Viewed')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_orders', to='main_app.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Photographer Order',
                'verbose_name_plural': 'Photographer Orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('is_photographer', models.BooleanField(default=False, verbose_name='Is Photographer')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='main_app.region', verbose_name='Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Access',
                'verbose_name_plural': 'Users Access',
                'ordering': ['id'],
                'unique_together': {('user', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='Banner', max_length=128, verbose_name='Title')),
                ('type_banner', models.CharField(choices=[('#1', '#1'), ('#2', '#2'), ('#3', '#3'), ('#4', '#4'), ('#5', '#5')], default='#1', max_length=3, verbose_name='Type Banner')),
                ('image', models.ImageField(upload_to=main_app.utilities.get_banner_path, verbose_name='Image')),
                ('url_address', models.URLField(verbose_name='URL Address')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main_app.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['type_banner'],
                'unique_together': {('region', 'type_banner')},
            },
        ),
    ]
