# Generated by Django 3.2.8 on 2021-11-06 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.utilities
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=news.utilities.get_news_path, verbose_name='Image')),
                ('owner', models.IntegerField(verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Title')),
                ('title_ru', models.CharField(db_index=True, max_length=128, verbose_name='Заглавие')),
                ('title_uk', models.CharField(db_index=True, max_length=128, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('main_image', models.ImageField(upload_to=news.utilities.get_news_path, verbose_name='Main Image')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_ru', models.TextField(verbose_name='Cодержание')),
                ('content_uk', models.TextField(verbose_name='Зміст')),
                ('num_views', models.IntegerField(default=0, verbose_name='Num Views')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main_app.region', verbose_name='Region')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'One News',
                'verbose_name_plural': 'News',
                'ordering': ['-date_published'],
            },
        ),
    ]
