# Generated by Django 3.2.8 on 2021-11-06 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import video_reports.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Title')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('pay_to_photographer', models.IntegerField(db_index=True, default=0, verbose_name='Pay to Photographer')),
                ('pay_to_portal', models.IntegerField(db_index=True, default=0, verbose_name='Pay to Portal')),
                ('image', models.ImageField(upload_to=video_reports.utilities.get_videoreport_path, verbose_name='Image')),
                ('url_address', models.URLField(verbose_name='URL Address')),
                ('num_views', models.IntegerField(default=0, verbose_name='Num Views')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoreports', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoreports', to='places.place', verbose_name='Place')),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videoreports', to='main_app.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Videoreport',
                'verbose_name_plural': 'Videoreports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, verbose_name='Is like')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_like', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('video_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_like', to='video_reports.videoreport', verbose_name='Videoreport')),
            ],
            options={
                'verbose_name': 'Video Like',
                'verbose_name_plural': 'Video Likes',
                'ordering': ['-id'],
                'unique_together': {('user', 'video_report')},
            },
        ),
    ]
